// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/nacl-org/nacl-cloud-go/internal/config"
	"github.com/nacl-org/nacl-cloud-go/internal/engineclient"
	"github.com/nacl-org/nacl-cloud-go/internal/handler"
	"github.com/nacl-org/nacl-cloud-go/internal/middleware"
	"github.com/nacl-org/nacl-cloud-go/internal/repository"
	"github.com/nacl-org/nacl-cloud-go/internal/service"
)

// Injectors from wire.go:

// InitializeApp resolves all service dependencies at compile-time and returns the bootstrapped App.
func InitializeApp() (*App, func(), error) {
	app := NewFiberApp()
	configConfig, err := config.NewConfig()
	if err != nil {
		return nil, nil, err
	}
	db, cleanup, err := repository.NewPostgresDatabase(configConfig)
	if err != nil {
		return nil, nil, err
	}
	clientConn, cleanup2, err := engineclient.NewEngineClient(configConfig)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	userRepository := repository.NewUserRepository(db)
	userService := service.NewUserService(userRepository)
	userHandler := handler.NewUserHandler(userService)
	workspaceRepository := repository.NewWorkspaceRepository(db)
	workspaceService := service.NewWorkspaceService(workspaceRepository)
	workspaceHandler := handler.NewWorkspaceHandler(workspaceService)
	telemetryRepository := repository.NewTelemetryRepository(db)
	telemetryService := service.NewTelemetryService(telemetryRepository, clientConn, db)
	telemetryHandler := handler.NewTelemetryHandler(telemetryService, configConfig)
	clerkAuthMiddleware := middleware.NewClerkAuthMiddleware(db)
	mainApp := NewApp(app, db, clientConn, configConfig, userHandler, workspaceHandler, telemetryHandler, clerkAuthMiddleware)
	return mainApp, func() {
		cleanup2()
		cleanup()
	}, nil
}
