// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.1
// source: engine.proto

package enginev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CompileSchemaRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SchemaContent string                 `protobuf:"bytes,1,opt,name=schema_content,json=schemaContent,proto3" json:"schema_content,omitempty"` // Raw text of the schema.infra file
	Environment   string                 `protobuf:"bytes,2,opt,name=environment,proto3" json:"environment,omitempty"`                          // Target environment (production, staging, etc.)
	TenantId      string                 `protobuf:"bytes,3,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`                // Workspace tenant ID context
	Settings      *WorkspaceSettings     `protobuf:"bytes,4,opt,name=settings,proto3" json:"settings,omitempty"`                                // User-configured compiler/workspace settings
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompileSchemaRequest) Reset() {
	*x = CompileSchemaRequest{}
	mi := &file_engine_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompileSchemaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompileSchemaRequest) ProtoMessage() {}

func (x *CompileSchemaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_engine_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompileSchemaRequest.ProtoReflect.Descriptor instead.
func (*CompileSchemaRequest) Descriptor() ([]byte, []int) {
	return file_engine_proto_rawDescGZIP(), []int{0}
}

func (x *CompileSchemaRequest) GetSchemaContent() string {
	if x != nil {
		return x.SchemaContent
	}
	return ""
}

func (x *CompileSchemaRequest) GetEnvironment() string {
	if x != nil {
		return x.Environment
	}
	return ""
}

func (x *CompileSchemaRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *CompileSchemaRequest) GetSettings() *WorkspaceSettings {
	if x != nil {
		return x.Settings
	}
	return nil
}

type CompileSchemaResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ExecutionId    string                 `protobuf:"bytes,1,opt,name=execution_id,json=executionId,proto3" json:"execution_id,omitempty"`           // Generated unique tracking ID
	CompiledDdl    string                 `protobuf:"bytes,2,opt,name=compiled_ddl,json=compiledDdl,proto3" json:"compiled_ddl,omitempty"`           // Sorted, optimized DDL statement
	ReclaimedBytes uint64                 `protobuf:"varint,3,opt,name=reclaimed_bytes,json=reclaimedBytes,proto3" json:"reclaimed_bytes,omitempty"` // Storage bytes saved (padding reduction)
	Spans          *CompilerSpans         `protobuf:"bytes,4,opt,name=spans,proto3" json:"spans,omitempty"`                                          // Performance latency compilation metrics
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CompileSchemaResponse) Reset() {
	*x = CompileSchemaResponse{}
	mi := &file_engine_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompileSchemaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompileSchemaResponse) ProtoMessage() {}

func (x *CompileSchemaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_engine_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompileSchemaResponse.ProtoReflect.Descriptor instead.
func (*CompileSchemaResponse) Descriptor() ([]byte, []int) {
	return file_engine_proto_rawDescGZIP(), []int{1}
}

func (x *CompileSchemaResponse) GetExecutionId() string {
	if x != nil {
		return x.ExecutionId
	}
	return ""
}

func (x *CompileSchemaResponse) GetCompiledDdl() string {
	if x != nil {
		return x.CompiledDdl
	}
	return ""
}

func (x *CompileSchemaResponse) GetReclaimedBytes() uint64 {
	if x != nil {
		return x.ReclaimedBytes
	}
	return 0
}

func (x *CompileSchemaResponse) GetSpans() *CompilerSpans {
	if x != nil {
		return x.Spans
	}
	return nil
}

type CompilerSpans struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	FrontendParseUs    uint64                 `protobuf:"varint,1,opt,name=frontend_parse_us,json=frontendParseUs,proto3" json:"frontend_parse_us,omitempty"`
	TopologicalSortUs  uint64                 `protobuf:"varint,2,opt,name=topological_sort_us,json=topologicalSortUs,proto3" json:"topological_sort_us,omitempty"`
	DdlGenerationUs    uint64                 `protobuf:"varint,3,opt,name=ddl_generation_us,json=ddlGenerationUs,proto3" json:"ddl_generation_us,omitempty"`
	TotalCompilationUs uint64                 `protobuf:"varint,4,opt,name=total_compilation_us,json=totalCompilationUs,proto3" json:"total_compilation_us,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *CompilerSpans) Reset() {
	*x = CompilerSpans{}
	mi := &file_engine_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompilerSpans) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompilerSpans) ProtoMessage() {}

func (x *CompilerSpans) ProtoReflect() protoreflect.Message {
	mi := &file_engine_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompilerSpans.ProtoReflect.Descriptor instead.
func (*CompilerSpans) Descriptor() ([]byte, []int) {
	return file_engine_proto_rawDescGZIP(), []int{2}
}

func (x *CompilerSpans) GetFrontendParseUs() uint64 {
	if x != nil {
		return x.FrontendParseUs
	}
	return 0
}

func (x *CompilerSpans) GetTopologicalSortUs() uint64 {
	if x != nil {
		return x.TopologicalSortUs
	}
	return 0
}

func (x *CompilerSpans) GetDdlGenerationUs() uint64 {
	if x != nil {
		return x.DdlGenerationUs
	}
	return 0
}

func (x *CompilerSpans) GetTotalCompilationUs() uint64 {
	if x != nil {
		return x.TotalCompilationUs
	}
	return 0
}

type LintSchemaRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SchemaContent string                 `protobuf:"bytes,1,opt,name=schema_content,json=schemaContent,proto3" json:"schema_content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LintSchemaRequest) Reset() {
	*x = LintSchemaRequest{}
	mi := &file_engine_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LintSchemaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LintSchemaRequest) ProtoMessage() {}

func (x *LintSchemaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_engine_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LintSchemaRequest.ProtoReflect.Descriptor instead.
func (*LintSchemaRequest) Descriptor() ([]byte, []int) {
	return file_engine_proto_rawDescGZIP(), []int{3}
}

func (x *LintSchemaRequest) GetSchemaContent() string {
	if x != nil {
		return x.SchemaContent
	}
	return ""
}

type LintSchemaResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HasErrors     bool                   `protobuf:"varint,1,opt,name=has_errors,json=hasErrors,proto3" json:"has_errors,omitempty"`
	Errors        []*ValidationError     `protobuf:"bytes,2,rep,name=errors,proto3" json:"errors,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LintSchemaResponse) Reset() {
	*x = LintSchemaResponse{}
	mi := &file_engine_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LintSchemaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LintSchemaResponse) ProtoMessage() {}

func (x *LintSchemaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_engine_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LintSchemaResponse.ProtoReflect.Descriptor instead.
func (*LintSchemaResponse) Descriptor() ([]byte, []int) {
	return file_engine_proto_rawDescGZIP(), []int{4}
}

func (x *LintSchemaResponse) GetHasErrors() bool {
	if x != nil {
		return x.HasErrors
	}
	return false
}

func (x *LintSchemaResponse) GetErrors() []*ValidationError {
	if x != nil {
		return x.Errors
	}
	return nil
}

type ValidationError struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Severity      string                 `protobuf:"bytes,1,opt,name=severity,proto3" json:"severity,omitempty"`                        // ERROR, WARNING, INFO
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`                          // Human-readable issue description
	LineNumber    uint32                 `protobuf:"varint,3,opt,name=line_number,json=lineNumber,proto3" json:"line_number,omitempty"` // Location context
	ColumnName    string                 `protobuf:"bytes,4,opt,name=column_name,json=columnName,proto3" json:"column_name,omitempty"`  // Entity affected
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidationError) Reset() {
	*x = ValidationError{}
	mi := &file_engine_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidationError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidationError) ProtoMessage() {}

func (x *ValidationError) ProtoReflect() protoreflect.Message {
	mi := &file_engine_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidationError.ProtoReflect.Descriptor instead.
func (*ValidationError) Descriptor() ([]byte, []int) {
	return file_engine_proto_rawDescGZIP(), []int{5}
}

func (x *ValidationError) GetSeverity() string {
	if x != nil {
		return x.Severity
	}
	return ""
}

func (x *ValidationError) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ValidationError) GetLineNumber() uint32 {
	if x != nil {
		return x.LineNumber
	}
	return 0
}

func (x *ValidationError) GetColumnName() string {
	if x != nil {
		return x.ColumnName
	}
	return ""
}

type VerifySafetyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RawDdl        string                 `protobuf:"bytes,1,opt,name=raw_ddl,json=rawDdl,proto3" json:"raw_ddl,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifySafetyRequest) Reset() {
	*x = VerifySafetyRequest{}
	mi := &file_engine_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifySafetyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifySafetyRequest) ProtoMessage() {}

func (x *VerifySafetyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_engine_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifySafetyRequest.ProtoReflect.Descriptor instead.
func (*VerifySafetyRequest) Descriptor() ([]byte, []int) {
	return file_engine_proto_rawDescGZIP(), []int{6}
}

func (x *VerifySafetyRequest) GetRawDdl() string {
	if x != nil {
		return x.RawDdl
	}
	return ""
}

type VerifySafetyResponse struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	RiskLevel             string                 `protobuf:"bytes,1,opt,name=risk_level,json=riskLevel,proto3" json:"risk_level,omitempty"`   // TRIVIAL, MODERATE, HIGH, CRITICAL
	RiskScore             float64                `protobuf:"fixed64,2,opt,name=risk_score,json=riskScore,proto3" json:"risk_score,omitempty"` // Numerical score between 0.0 and 10.0
	HeavyRewritesDetected bool                   `protobuf:"varint,3,opt,name=heavy_rewrites_detected,json=heavyRewritesDetected,proto3" json:"heavy_rewrites_detected,omitempty"`
	ExclusiveLocks        []string               `protobuf:"bytes,4,rep,name=exclusive_locks,json=exclusiveLocks,proto3" json:"exclusive_locks,omitempty"` // List of table names that will be locked during execution
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *VerifySafetyResponse) Reset() {
	*x = VerifySafetyResponse{}
	mi := &file_engine_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifySafetyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifySafetyResponse) ProtoMessage() {}

func (x *VerifySafetyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_engine_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifySafetyResponse.ProtoReflect.Descriptor instead.
func (*VerifySafetyResponse) Descriptor() ([]byte, []int) {
	return file_engine_proto_rawDescGZIP(), []int{7}
}

func (x *VerifySafetyResponse) GetRiskLevel() string {
	if x != nil {
		return x.RiskLevel
	}
	return ""
}

func (x *VerifySafetyResponse) GetRiskScore() float64 {
	if x != nil {
		return x.RiskScore
	}
	return 0
}

func (x *VerifySafetyResponse) GetHeavyRewritesDetected() bool {
	if x != nil {
		return x.HeavyRewritesDetected
	}
	return false
}

func (x *VerifySafetyResponse) GetExclusiveLocks() []string {
	if x != nil {
		return x.ExclusiveLocks
	}
	return nil
}

type WorkspaceSettings struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	PaddingEnabled      bool                   `protobuf:"varint,1,opt,name=padding_enabled,json=paddingEnabled,proto3" json:"padding_enabled,omitempty"`
	ChunkingEnabled     bool                   `protobuf:"varint,2,opt,name=chunking_enabled,json=chunkingEnabled,proto3" json:"chunking_enabled,omitempty"`
	DefaultChunkSize    int32                  `protobuf:"varint,3,opt,name=default_chunk_size,json=defaultChunkSize,proto3" json:"default_chunk_size,omitempty"`
	LockTimeoutMs       int32                  `protobuf:"varint,4,opt,name=lock_timeout_ms,json=lockTimeoutMs,proto3" json:"lock_timeout_ms,omitempty"`
	MaxRetries          int32                  `protobuf:"varint,5,opt,name=max_retries,json=maxRetries,proto3" json:"max_retries,omitempty"`
	SreApprovalRequired bool                   `protobuf:"varint,6,opt,name=sre_approval_required,json=sreApprovalRequired,proto3" json:"sre_approval_required,omitempty"`
	SandboxDryRun       bool                   `protobuf:"varint,7,opt,name=sandbox_dry_run,json=sandboxDryRun,proto3" json:"sandbox_dry_run,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *WorkspaceSettings) Reset() {
	*x = WorkspaceSettings{}
	mi := &file_engine_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkspaceSettings) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkspaceSettings) ProtoMessage() {}

func (x *WorkspaceSettings) ProtoReflect() protoreflect.Message {
	mi := &file_engine_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkspaceSettings.ProtoReflect.Descriptor instead.
func (*WorkspaceSettings) Descriptor() ([]byte, []int) {
	return file_engine_proto_rawDescGZIP(), []int{8}
}

func (x *WorkspaceSettings) GetPaddingEnabled() bool {
	if x != nil {
		return x.PaddingEnabled
	}
	return false
}

func (x *WorkspaceSettings) GetChunkingEnabled() bool {
	if x != nil {
		return x.ChunkingEnabled
	}
	return false
}

func (x *WorkspaceSettings) GetDefaultChunkSize() int32 {
	if x != nil {
		return x.DefaultChunkSize
	}
	return 0
}

func (x *WorkspaceSettings) GetLockTimeoutMs() int32 {
	if x != nil {
		return x.LockTimeoutMs
	}
	return 0
}

func (x *WorkspaceSettings) GetMaxRetries() int32 {
	if x != nil {
		return x.MaxRetries
	}
	return 0
}

func (x *WorkspaceSettings) GetSreApprovalRequired() bool {
	if x != nil {
		return x.SreApprovalRequired
	}
	return false
}

func (x *WorkspaceSettings) GetSandboxDryRun() bool {
	if x != nil {
		return x.SandboxDryRun
	}
	return false
}

var File_engine_proto protoreflect.FileDescriptor

const file_engine_proto_rawDesc = "" +
	"\n" +
	"\fengine.proto\x12\x0enacl.engine.v1\"\xbb\x01\n" +
	"\x14CompileSchemaRequest\x12%\n" +
	"\x0eschema_content\x18\x01 \x01(\tR\rschemaContent\x12 \n" +
	"\venvironment\x18\x02 \x01(\tR\venvironment\x12\x1b\n" +
	"\ttenant_id\x18\x03 \x01(\tR\btenantId\x12=\n" +
	"\bsettings\x18\x04 \x01(\v2!.nacl.engine.v1.WorkspaceSettingsR\bsettings\"\xbb\x01\n" +
	"\x15CompileSchemaResponse\x12!\n" +
	"\fexecution_id\x18\x01 \x01(\tR\vexecutionId\x12!\n" +
	"\fcompiled_ddl\x18\x02 \x01(\tR\vcompiledDdl\x12'\n" +
	"\x0freclaimed_bytes\x18\x03 \x01(\x04R\x0ereclaimedBytes\x123\n" +
	"\x05spans\x18\x04 \x01(\v2\x1d.nacl.engine.v1.CompilerSpansR\x05spans\"\xc9\x01\n" +
	"\rCompilerSpans\x12*\n" +
	"\x11frontend_parse_us\x18\x01 \x01(\x04R\x0ffrontendParseUs\x12.\n" +
	"\x13topological_sort_us\x18\x02 \x01(\x04R\x11topologicalSortUs\x12*\n" +
	"\x11ddl_generation_us\x18\x03 \x01(\x04R\x0fddlGenerationUs\x120\n" +
	"\x14total_compilation_us\x18\x04 \x01(\x04R\x12totalCompilationUs\":\n" +
	"\x11LintSchemaRequest\x12%\n" +
	"\x0eschema_content\x18\x01 \x01(\tR\rschemaContent\"l\n" +
	"\x12LintSchemaResponse\x12\x1d\n" +
	"\n" +
	"has_errors\x18\x01 \x01(\bR\thasErrors\x127\n" +
	"\x06errors\x18\x02 \x03(\v2\x1f.nacl.engine.v1.ValidationErrorR\x06errors\"\x89\x01\n" +
	"\x0fValidationError\x12\x1a\n" +
	"\bseverity\x18\x01 \x01(\tR\bseverity\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1f\n" +
	"\vline_number\x18\x03 \x01(\rR\n" +
	"lineNumber\x12\x1f\n" +
	"\vcolumn_name\x18\x04 \x01(\tR\n" +
	"columnName\".\n" +
	"\x13VerifySafetyRequest\x12\x17\n" +
	"\araw_ddl\x18\x01 \x01(\tR\x06rawDdl\"\xb5\x01\n" +
	"\x14VerifySafetyResponse\x12\x1d\n" +
	"\n" +
	"risk_level\x18\x01 \x01(\tR\triskLevel\x12\x1d\n" +
	"\n" +
	"risk_score\x18\x02 \x01(\x01R\triskScore\x126\n" +
	"\x17heavy_rewrites_detected\x18\x03 \x01(\bR\x15heavyRewritesDetected\x12'\n" +
	"\x0fexclusive_locks\x18\x04 \x03(\tR\x0eexclusiveLocks\"\xba\x02\n" +
	"\x11WorkspaceSettings\x12'\n" +
	"\x0fpadding_enabled\x18\x01 \x01(\bR\x0epaddingEnabled\x12)\n" +
	"\x10chunking_enabled\x18\x02 \x01(\bR\x0fchunkingEnabled\x12,\n" +
	"\x12default_chunk_size\x18\x03 \x01(\x05R\x10defaultChunkSize\x12&\n" +
	"\x0flock_timeout_ms\x18\x04 \x01(\x05R\rlockTimeoutMs\x12\x1f\n" +
	"\vmax_retries\x18\x05 \x01(\x05R\n" +
	"maxRetries\x122\n" +
	"\x15sre_approval_required\x18\x06 \x01(\bR\x13sreApprovalRequired\x12&\n" +
	"\x0fsandbox_dry_run\x18\a \x01(\bR\rsandboxDryRun2\x9d\x02\n" +
	"\rEngineService\x12\\\n" +
	"\rCompileSchema\x12$.nacl.engine.v1.CompileSchemaRequest\x1a%.nacl.engine.v1.CompileSchemaResponse\x12S\n" +
	"\n" +
	"LintSchema\x12!.nacl.engine.v1.LintSchemaRequest\x1a\".nacl.engine.v1.LintSchemaResponse\x12Y\n" +
	"\fVerifySafety\x12#.nacl.engine.v1.VerifySafetyRequest\x1a$.nacl.engine.v1.VerifySafetyResponseB=Z;github.com/nacl-org/nacl-cloud-go/pkg/pb/engine/v1;enginev1b\x06proto3"

var (
	file_engine_proto_rawDescOnce sync.Once
	file_engine_proto_rawDescData []byte
)

func file_engine_proto_rawDescGZIP() []byte {
	file_engine_proto_rawDescOnce.Do(func() {
		file_engine_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_engine_proto_rawDesc), len(file_engine_proto_rawDesc)))
	})
	return file_engine_proto_rawDescData
}

var file_engine_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_engine_proto_goTypes = []any{
	(*CompileSchemaRequest)(nil),  // 0: nacl.engine.v1.CompileSchemaRequest
	(*CompileSchemaResponse)(nil), // 1: nacl.engine.v1.CompileSchemaResponse
	(*CompilerSpans)(nil),         // 2: nacl.engine.v1.CompilerSpans
	(*LintSchemaRequest)(nil),     // 3: nacl.engine.v1.LintSchemaRequest
	(*LintSchemaResponse)(nil),    // 4: nacl.engine.v1.LintSchemaResponse
	(*ValidationError)(nil),       // 5: nacl.engine.v1.ValidationError
	(*VerifySafetyRequest)(nil),   // 6: nacl.engine.v1.VerifySafetyRequest
	(*VerifySafetyResponse)(nil),  // 7: nacl.engine.v1.VerifySafetyResponse
	(*WorkspaceSettings)(nil),     // 8: nacl.engine.v1.WorkspaceSettings
}
var file_engine_proto_depIdxs = []int32{
	8, // 0: nacl.engine.v1.CompileSchemaRequest.settings:type_name -> nacl.engine.v1.WorkspaceSettings
	2, // 1: nacl.engine.v1.CompileSchemaResponse.spans:type_name -> nacl.engine.v1.CompilerSpans
	5, // 2: nacl.engine.v1.LintSchemaResponse.errors:type_name -> nacl.engine.v1.ValidationError
	0, // 3: nacl.engine.v1.EngineService.CompileSchema:input_type -> nacl.engine.v1.CompileSchemaRequest
	3, // 4: nacl.engine.v1.EngineService.LintSchema:input_type -> nacl.engine.v1.LintSchemaRequest
	6, // 5: nacl.engine.v1.EngineService.VerifySafety:input_type -> nacl.engine.v1.VerifySafetyRequest
	1, // 6: nacl.engine.v1.EngineService.CompileSchema:output_type -> nacl.engine.v1.CompileSchemaResponse
	4, // 7: nacl.engine.v1.EngineService.LintSchema:output_type -> nacl.engine.v1.LintSchemaResponse
	7, // 8: nacl.engine.v1.EngineService.VerifySafety:output_type -> nacl.engine.v1.VerifySafetyResponse
	6, // [6:9] is the sub-list for method output_type
	3, // [3:6] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_engine_proto_init() }
func file_engine_proto_init() {
	if File_engine_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_engine_proto_rawDesc), len(file_engine_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_engine_proto_goTypes,
		DependencyIndexes: file_engine_proto_depIdxs,
		MessageInfos:      file_engine_proto_msgTypes,
	}.Build()
	File_engine_proto = out.File
	file_engine_proto_goTypes = nil
	file_engine_proto_depIdxs = nil
}
