// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v4.25.1
// source: engine.proto

package enginev1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	EngineService_CompileSchema_FullMethodName = "/nacl.engine.v1.EngineService/CompileSchema"
	EngineService_LintSchema_FullMethodName    = "/nacl.engine.v1.EngineService/LintSchema"
	EngineService_VerifySafety_FullMethodName  = "/nacl.engine.v1.EngineService/VerifySafety"
)

// EngineServiceClient is the client API for EngineService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// The core database compiler and verification service
type EngineServiceClient interface {
	// Parses schema.infra declarative target state and calculates layout optimizations
	CompileSchema(ctx context.Context, in *CompileSchemaRequest, opts ...grpc.CallOption) (*CompileSchemaResponse, error)
	// Performs static analysis and syntax linting on schema.infra definitions
	LintSchema(ctx context.Context, in *LintSchemaRequest, opts ...grpc.CallOption) (*LintSchemaResponse, error)
	// Performs SRE risk and lock analysis on a proposed DDL migration script
	VerifySafety(ctx context.Context, in *VerifySafetyRequest, opts ...grpc.CallOption) (*VerifySafetyResponse, error)
}

type engineServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewEngineServiceClient(cc grpc.ClientConnInterface) EngineServiceClient {
	return &engineServiceClient{cc}
}

func (c *engineServiceClient) CompileSchema(ctx context.Context, in *CompileSchemaRequest, opts ...grpc.CallOption) (*CompileSchemaResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CompileSchemaResponse)
	err := c.cc.Invoke(ctx, EngineService_CompileSchema_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *engineServiceClient) LintSchema(ctx context.Context, in *LintSchemaRequest, opts ...grpc.CallOption) (*LintSchemaResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LintSchemaResponse)
	err := c.cc.Invoke(ctx, EngineService_LintSchema_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *engineServiceClient) VerifySafety(ctx context.Context, in *VerifySafetyRequest, opts ...grpc.CallOption) (*VerifySafetyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VerifySafetyResponse)
	err := c.cc.Invoke(ctx, EngineService_VerifySafety_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EngineServiceServer is the server API for EngineService service.
// All implementations must embed UnimplementedEngineServiceServer
// for forward compatibility.
//
// The core database compiler and verification service
type EngineServiceServer interface {
	// Parses schema.infra declarative target state and calculates layout optimizations
	CompileSchema(context.Context, *CompileSchemaRequest) (*CompileSchemaResponse, error)
	// Performs static analysis and syntax linting on schema.infra definitions
	LintSchema(context.Context, *LintSchemaRequest) (*LintSchemaResponse, error)
	// Performs SRE risk and lock analysis on a proposed DDL migration script
	VerifySafety(context.Context, *VerifySafetyRequest) (*VerifySafetyResponse, error)
	mustEmbedUnimplementedEngineServiceServer()
}

// UnimplementedEngineServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedEngineServiceServer struct{}

func (UnimplementedEngineServiceServer) CompileSchema(context.Context, *CompileSchemaRequest) (*CompileSchemaResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CompileSchema not implemented")
}
func (UnimplementedEngineServiceServer) LintSchema(context.Context, *LintSchemaRequest) (*LintSchemaResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method LintSchema not implemented")
}
func (UnimplementedEngineServiceServer) VerifySafety(context.Context, *VerifySafetyRequest) (*VerifySafetyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method VerifySafety not implemented")
}
func (UnimplementedEngineServiceServer) mustEmbedUnimplementedEngineServiceServer() {}
func (UnimplementedEngineServiceServer) testEmbeddedByValue()                       {}

// UnsafeEngineServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to EngineServiceServer will
// result in compilation errors.
type UnsafeEngineServiceServer interface {
	mustEmbedUnimplementedEngineServiceServer()
}

func RegisterEngineServiceServer(s grpc.ServiceRegistrar, srv EngineServiceServer) {
	// If the following call panics, it indicates UnimplementedEngineServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&EngineService_ServiceDesc, srv)
}

func _EngineService_CompileSchema_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CompileSchemaRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EngineServiceServer).CompileSchema(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EngineService_CompileSchema_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EngineServiceServer).CompileSchema(ctx, req.(*CompileSchemaRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EngineService_LintSchema_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LintSchemaRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EngineServiceServer).LintSchema(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EngineService_LintSchema_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EngineServiceServer).LintSchema(ctx, req.(*LintSchemaRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EngineService_VerifySafety_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VerifySafetyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EngineServiceServer).VerifySafety(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EngineService_VerifySafety_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EngineServiceServer).VerifySafety(ctx, req.(*VerifySafetyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// EngineService_ServiceDesc is the grpc.ServiceDesc for EngineService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var EngineService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "nacl.engine.v1.EngineService",
	HandlerType: (*EngineServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CompileSchema",
			Handler:    _EngineService_CompileSchema_Handler,
		},
		{
			MethodName: "LintSchema",
			Handler:    _EngineService_LintSchema_Handler,
		},
		{
			MethodName: "VerifySafety",
			Handler:    _EngineService_VerifySafety_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "engine.proto",
}
